# ReplicaSet Block

apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: myapp-replicaset
  labels:
    env: Production

# labels for replicaset & pod should be always same. Otherwise dployment will not occur.

# Pods block, to use Pods block , use template: & paste all data from metadat of pods file
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        env: Production

    spec:
      containers:
        - name: nginx-2-container
          image: nginx

  replicas: 3
  selector:
    matchLabels:
      env: Production


# To create replicas , run,

# kubectl create -f replicaSet.yml
# kubectl get replicaset
# kubectl get pods

# kubectl describe replicaset myapp-replicaset

# Try to delete one pods & see , a new pods was created & replace with old.
# kubectl delete pod "pod_name"

# Try to change replicas from 3 to replicas 6 by edit temporary file of replicas.
# kubectl edit replicaset myapp-replicaset

# Without modify replicaset.yml file or in temporary file.
# kubectl scale replicaset myapp-replicaset --relicas=2